In [20]:
import numpy as np
from numpy import linalg as LA
#import scipy
from scipy import linalg as la

In [22]:
cov_matrix =  np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
cov_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a = la.eig(cov_matrix)

In [24]:
a

(array([ 1.61168440e+01+0.j, -1.11684397e+00+0.j, -1.30367773e-15+0.j]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [141]:
a = np.array([(1,5), (3,3)])
a

array([[1, 5],
       [3, 3]])

In [104]:
d, v = la.eig(a)

In [105]:
v

array([[-0.85749293, -0.70710678],
       [ 0.51449576, -0.70710678]])

In [106]:
d

array([-2.+0.j,  6.+0.j])

In [101]:
v_d = v[0]*d[0]
v_d.tranpose()

AttributeError: 'numpy.ndarray' object has no attribute 'tranpose'

In [90]:
v[0]

array([-0.82456484, -0.41597356])

## 1. Matrix Eigenvalues Problem:

If a matrix is multiplied with a vector, it returns with another vector. When this returned vector is scaled vector, scale of the vector is eigenvalue of the matrix and the vector is eigenvector of the matrix.
\begin{equation*}
\ A  x  v  = \lambda x v
\end{equation*}
\begin{equation*}
\ (A - \lambda I)x v = 0
\end{equation*}

When A matrix is passed to la.linalg.eig function,it returns with an array of eigenvalues and list of eigenvectors
vectors in a matrix format.For example;

In [121]:
A = np.array([(1,5), (3,3)])  # A is a random matrix
eigenvalues, eigenvectors = la.eig(A)

In [111]:
eigenvalues # each elements corresponding another eigenvalues

array([-2.+0.j,  6.+0.j])

In [112]:
eigenvectors # each array corresponding another eigenvector

array([[-0.85749293, -0.70710678],
       [ 0.51449576, -0.70710678]])

In [122]:
np.dot(eigenvalues[0], eigenvectors[:,0])

array([ 1.71498585+0.j, -1.02899151+0.j])

In [123]:
np.dot(A, eigenvectors[:,0])

array([ 1.71498585, -1.02899151])

As the formula, multiply of matrix and eigenvector equals multiply of eigenvector and eigenvalue.

## 2. Formula of vector form of Covariance Matrix

In [125]:
vd = np.dot(eigenvalues[0], eigenvectors[:,0])

In [134]:
np.dot(vd, np.transpose(v[:,0]))

(-1.9999999999999996+0j)

AttributeError: 'list' object has no attribute 'T'

In [146]:
u

array([-0.85749293,  0.51449576])

In [148]:
a = np.array([1,2,3])

In [149]:
a.T

array([1, 2, 3])